### ISSUE TITLE
Installation does not work as described in README

### ISSUE THREAD

**Issue by sschuberth** [ossf/criticality_score#12]
I get:

```
$ pip3 install criticality-score
Collecting criticality-score
  Could not find a version that satisfies the requirement criticality-score (from versions: )
No matching distribution found for criticality-score
```

**Comment by inferno-chromium** [comment]
What version of python are you using, i put in >=3.7
you can also do ```python3 -m criticality_score.run --repo=<repo_url>```

**Comment by facontidavide** [comment]
Same problem here, on Ubuntu 18.04, since installed python version is 3.6.9

**Comment by inferno-chromium** [comment]
Ok fixed, should work now, i tested on a python:3.6 docker image.

**Comment by inferno-chromium** [comment]
It should work with regular `pip3 install criticality-score` now, can you try again @sschuberth

**Comment by sschuberth** [comment]
Confirmed to work now, thanks.
