### ISSUE TITLE
Make the "Public Data" list actually publicly browsable

### ISSUE THREAD

**Issue by licaon-kter** [ossf/criticality_score#13]
Right now it is hosted on a private server that requires an account.

Ref: https://storage.cloud.google.com/ossf-criticality-score

**Comment by inferno-chromium** [comment]
Try these, e.g.

https://storage.googleapis.com/ossf-criticality-score/<language>_top_200.csv
e.g.
https://storage.googleapis.com/ossf-criticality-score/c_top_200.csv

**Comment by licaon-kter** [comment]
Where are the languages listed? Eg. `erlang` fails

**Comment by inferno-chromium** [comment]
let me fix this properly, adding an index.html soonish

**Comment by inferno-chromium** [comment]
Please use 
https://commondatastorage.googleapis.com/ossf-criticality-score/index.html

**Comment by licaon-kter** [comment]
Thanks
