### ISSUE TITLE
Use project first commit date for created_since, instead of github project creation date

### ISSUE THREAD

**Issue by romen** [ossf/criticality_score#14]
For many projects the github creation date might not match the project creation date.

Would it be better to look at the date of the oldest commit in the repository? 

For example, for OpenSSL the computed `creation_since` value is 95 months, as the date of creation of a github mirror (`2013-01-15T22:34:48Z`), but the project is almost 22 years old (the first commit in the `master` branch dates back to `1998-12-21T10:52:45+00:00`)!

The cap for the field is 10 years anyway, so it's not that bad, but still it is one parameter in the equation that might be adjusted.

_**Edit:** this also affects other fields (e.g. `recent_releases`) when they are computed based on estimates based on the time since creation._

Thoughts?

**Comment by romen** [comment]
This also affects the `recent_releases` estimate!

OpenSSL doesn't use github releases, so it ends up using the fallback estimate for that field:
https://github.com/ossf/criticality_score/blob/59e449d5598de4f27a83070297e5779a4a3407b2/criticality_score/run.py#L96-L114

In a [thread](https://www.mail-archive.com/openssl-project@openssl.org/msg02316.html) discussing this on the openssl-project mailing list:

>> Not sure I understand the "Releases (last yr)" column which says we did
>> 41 releases - that's a number I can't reconcile with the actual number
>> of releases we did.
>>
>
>It seems to be an estimate based on the number of tags, as we don't do github releases:
>
>```
>RELEASE_LOOKBACK_DAYS=365
>(total_tags / days_since_creation) * RELEASE_LOOKBACK_DAYS
>```
>
>This is definitely skewed by considering the project 95 months old (2887 days) instead of ~264 months (8026 days).
>

**Comment by inferno-chromium** [comment]
Ok i agree, first commit date is a nice idea. For tags, yes this will change number slightly [still low score 0.5 for releases]. Will look into this some time, patches welcome!

**Comment by inferno-chromium** [comment]
Can someone please respond to openssl mailing list that this minor bug will be fixed, but it does not impact the result due to threshold, both of creation_date and release hit the max threshold, so outcome/result will be the same.

**Comment by romen** [comment]
> Can someone please respond to openssl mailing list that this minor bug will be fixed, but it does not impact the result due to threshold, both of creation_date and release hit the max threshold, so outcome/result will be the same.

I could send the email to update the discussion on the mailing list if you want, but are you sure about the message to convey? 

I tend to agree the impact won't be massive due to the threshold, but the created_since field threshold is documented as 120 months, so 95 although close is not being capped, which should result in a slight value change once it is fixed.

Anyway, just confirm what you want me to quote and I can forward it on the mailing list as an answer in the original thread. 

On a side note, anyone send an email to the openssl-project list, but it is moderated so it can take some time to go through the moderation stack depending on availability of the moderators and load of work. This is just to say that technically you don't really need me to forward your message (but I get it it's easier to make sure it is threaded in the existing discussion thread).

**Comment by inferno-chromium** [comment]
Yes just wanted to send this in existing mailing list discussion thread, would appreciate if you can send this (i am trying to subscribe, but still pending):

"Thanks for notifying us of the issue with incorrect project creation date issue, we do plan to look into it and see feasibility of picking the first commit date for accuracy. In case of openssl, it would have little to no-impact on criticality score, as other factors clearly indicate it is a super-critical project. These include things like users dependent on openssl library, number of project contributors and user activity in terms of issues filed, updated."

**Comment by romen** [comment]
Sent! Thank you for your answer!

Here is a mail-archive link to the message: https://www.mail-archive.com/openssl-project@openssl.org/msg02319.html

**Comment by inferno-chromium** [comment]
All csvs will be regenerated in the next week, starting on it now.
