### ISSUE TITLE
GeoTools not showing in top 200 for java projects, run criticality score on larger sample set

### ISSUE THREAD

**Issue by aaime** [ossf/criticality_score#15]
I looked at the top 200 Java projects, out of curiosity, to see if any of the projects I'm working on, like GeoTools, is included in the list. It was not, which is not an issue per se, but then I've computed the criticality score from command line, getting this:

```
criticality_score --repo "https://github.com/geotools/geotools"
name: geotools
url: https://github.com/geotools/geotools
language: Java
created_since: 111
updated_since: 0
contributor_count: 315
org_count: 6
commit_frequency: 9.7
recent_releases_count: 16
closed_issues_count: 150
updated_issues_count: 161
comment_frequency: 1.0
dependents_count: 337
criticality_score: 0.66477
```

The score alone would place the project at around position 100 of the top 200 projects. Since it's a no show, I'm wondering if there is any other criteria used to include/exclude projects, besides the pure score?

**Comment by inferno-chromium** [comment]
Will be re-generating the list. We were looking at top 1000 repos by stars and then sorting the data by criticality_score, we need to run this on a larger set so that Geotools show up correctly. Github api has some rate limit, so we will try our best to regenerate this in next few days.

**Comment by aflgo** [comment]
> Github api has some rate limit

Does this help: https://ghtorrent.org/ ?

**Comment by inferno-chromium** [comment]
Didnt know that aflgo@ , that looks like a gold mine!

**Comment by inferno-chromium** [comment]
> Happy to help! 👍
> 
> > GHTorrent is an effort to create a scalable, queriable, offline mirror of data offered through the Github REST API.
> 
> (switched accounts)

@mboehme - ideally we want to first sort first XK repos (e.g. 100K or even like 10K) by stars, then run criticality_score on them and publish like top 1000, that would be ideal. if you can help connect with ghtorrent folks who can run this sort of workload and generate this for the top5-10 languages, that would be very useful. it will solve issues like https://github.com/ossf/criticality_score/issues/20 as well.

**Comment by mboehme** [comment]
Will do. Getting back when I have something.

**Comment by inferno-chromium** [comment]
Tracking this in https://github.com/ossf/criticality_score/issues/33, even github search api has limitation, so will need to explore others like GHTorrent.

**Comment by inferno-chromium** [comment]
This is now fixed in http://commondatastorage.googleapis.com/ossf-criticality-score/java_top_200.csv

**Comment by aaime** [comment]
Thanks! GeoTools is not using GitHub for issue tracking, but Jira. Is the score considering it? Would it improve it we switched (not an easy thing to do by any measure mind, just wondering).

**Comment by inferno-chromium** [comment]
> Thanks! GeoTools is not using GitHub for issue tracking, but Jira. Is the score considering it? Would it improve it we switched (not an easy thing to do by any measure mind, just wondering).

Right now, it is not, but if you switch, it will definitely fix the score for it. We are looking at ways to check custom issue trackers, but it does not seem trivial, free feel to brainstorm with us in issue #21

**Comment by aaime** [comment]
Btw, I did run GeoServer too, has a higher score than GeoTools but does not show up:

```
name: geoserver
url: 
https://github.com/geoserver/geoserver

language: Java
created_since: 111
updated_since: 0
contributor_count: 339
org_count: 7
commit_frequency: 10.0
recent_releases_count: 16
closed_issues_count: 154
updated_issues_count: 167
comment_frequency: 0.8
dependents_count: 5829
criticality_score: 0.72083
```

Any idea why?

**Comment by inferno-chromium** [comment]
> Btw, I did run GeoServer too, has a higher score than GeoTools but does not show up:
> 
> ```
> name: geoserver
> url: 
> https://github.com/geoserver/geoserver
> 
> language: Java
> created_since: 111
> updated_since: 0
> contributor_count: 339
> org_count: 7
> commit_frequency: 10.0
> recent_releases_count: 16
> closed_issues_count: 154
> updated_issues_count: 167
> comment_frequency: 0.8
> dependents_count: 5829
> criticality_score: 0.72083
> ```
> 
> Any idea why?

All the language lists are getting regenerated now due to bug fixes [https://github.com/ossf/criticality_score/commit/fc1e96657c83fc64d5c4c306f185ff133bb00460], so please check back in another week (post holidays).
