### ISSUE TITLE
Add definition of criticality in the definition

### ISSUE THREAD

**Issue by ford--prefect** [ossf/criticality_score#19]
So far, it is not clear what criticality means to you. I see two possible different interpretations:
1) Criticality of a project for the software stack: How crucial is a project for the common software stack (as e.g. in https://xkcd.com/2347/).
2) Health of a project weighted with its significance for the software stack: Determines the health of a project w.r.t. maintenance.

I think you mean to use definition 2) since you are penalizing long times since last release etc, but IMHO your definition of criticality should be stated in the PDF explaining the algorithm, preferably as a first paragraph.

**Comment by inferno-chromium** [comment]
We don't mean 2). Criticality is defined in terms of project importance for the user. Releases is a very small weight in the overall algo (0.5) and is just meant to see that a project is important if it is doing periodic releases that are used by a user.
This one is slightly subjective, but given its low weight it does not impact the results much.

Other factors such as contributor count, user issue filing/updates, dependents count are the more important metrics (higher weights).

Fixed the definition in https://github.com/ossf/criticality_score/commit/d991b7cbe5383155a6278c597b1deeb0ed94d94c
