### ISSUE TITLE
Language implementation is less critical than language project generator, create list for TypeScript projects inside JS list.

### ISSUE THREAD

**Issue by DanielRosenwasser** [ossf/criticality_score#22]
tsdx, a TypeScript project generator, appears in the top 200 list for JavaScript packages; however, TypeScript itself does not. That *seems* somewhat counterintuitive.

**Comment by inferno-chromium** [comment]
So, Github classifies Typescript as its own language and we need to create a typescript specific list. then, https://github.com/microsoft/TypeScript will show on the top, we will work on that.

**Comment by DanielRosenwasser** [comment]
Gotcha, though it'd probably be a good idea to factor TypeScript projects into JavaScript projects. The TS project community is really a subset of the JS community.

**Comment by inferno-chromium** [comment]
> Gotcha, though it'd probably be a good idea to factor TypeScript projects into JavaScript projects. The TS project community is really a subset of the JS community.

Sounds good, let me start on that, maybe take a day or two. Sorry github api is very slow with rate limit.

**Comment by inferno-chromium** [comment]
Fixed in http://commondatastorage.googleapis.com/ossf-criticality-score/js_top_200.csv [contains both Javascript and Typescript projects)
