### ISSUE TITLE
JDK is less important than 11 projects

### ISSUE THREAD

**Issue by bmarwell** [ossf/criticality_score#24]
Hi,

I just saw that the OpenJDK repository is less important that 11 java projects.
Maybe due to the fact that they:

* are not a declared dependency
* https://github.com/ossf/criticality_score/issues/14
* external issue tracker
* Some parts split into other repositories

Probably the same for other languages

**Comment by inferno-chromium** [comment]
Yes plan to look more into it as part of https://github.com/ossf/criticality_score/issues/21. Closing this as dup, and will track as part of that bug. This is a hard problem, but need to atleast support most common usecases.
