### ISSUE TITLE
Maven and Gradle not in the Top 2000 java list

### ISSUE THREAD

**Issue by bmarwell** [ossf/criticality_score#25]
Hi,

I just saw that the Maven and Gradle projects are less important that 2000 java projects where they are used in as a build tool.
Maybe due to the fact that they:

* are not a declared dependency
* https://github.com/ossf/criticality_score/issues/14
* https://github.com/ossf/criticality_score/issues/23
* external issue tracker
* All the parts (pluggable, not a dependency!) [are split into many repositories](https://github.com/apache/?q=maven&type=source&language=java)
* Mosten downloaded via maven.org, sdkman, package systems, etc

Probably the same for other languages and build-tools, but haven’t checked.

**Comment by melix** [comment]
For Gradle, I ran the CLI tool and it gives:

```
name: gradle
url: https://github.com/gradle/gradle
language: Groovy
created_since: 137
updated_since: 0
contributor_count: 583
org_count: 5
commit_frequency: 184.3
recent_releases_count: 41
closed_issues_count: 1366
updated_issues_count: 2216
comment_frequency: 1.9
dependents_count: 40828
criticality_score: 0.86789
```

I think it's not listed because it says "Language Groovy", where most of the _production code_ is Java: we have more tests than production code, and tests are indeed written in Groovy.

**Comment by inferno-chromium** [comment]
Need to add Groovy language in Java language list, that should fix Gradle.

Maven, i will investigate more.

**Comment by melix** [comment]
Adding Groovy will help but it doesn't change the fact that if any protect uses Gradle or Maven to build, then it should minimally count as a dependency to them.

**Comment by inferno-chromium** [comment]
> Adding Groovy will help but it doesn't change the fact that if any protect uses Gradle or Maven to build, then it should minimally count as a dependency to them.

Yes we are thinking of dependencies, see Issue 31 and Issue 8 [not adding hash to avoid cross linking].

**Comment by inferno-chromium** [comment]
Graddy and other Groovy languages are added in http://commondatastorage.googleapis.com/ossf-criticality-score/java_top_200.csv

Maven will be added once https://github.com/ossf/criticality_score/issues/33 is fixed, tracking it there.

**Comment by inferno-chromium** [comment]
This is now fixed in http://commondatastorage.googleapis.com/ossf-criticality-score/java_top_200.csv
