### ISSUE TITLE
Something wrong with Ansible criticality_score in python chart

### ISSUE THREAD

**Issue by Nklya** [ossf/criticality_score#28]
Hi,
Thank you for the project.

I believe there is some error in Python chart.
How there could be no Ansible at all, and Salt is listed on top?

I checked this [file](gs://ossf-criticality-score/python_top_200.csv) and run `criticality_score` locally and got these results:
```
name: ansible
url: https://github.com/ansible/ansible
language: Python
created_since: 107
updated_since: 0
contributor_count: 6317
org_count: 8
commit_frequency: 45.3
recent_releases_count: 39
closed_issues_count: 3112
updated_issues_count: 4070
comment_frequency: 0.9
dependents_count: 67606
criticality_score: 0.92169
``` 

```
name: salt
url: https://github.com/saltstack/salt
language: Python
created_since: 119
updated_since: 0
contributor_count: 3635
org_count: 7
commit_frequency: 64.9
recent_releases_count: 18
closed_issues_count: 861
updated_issues_count: 1839
comment_frequency: 1.1
dependents_count: 20966
criticality_score: 0.87833
```

So, as you can see, Ansible has a way bigger criticality_score (0.92169), why then it's not listed at all?

**Comment by inferno-chromium** [comment]
Yes there was a bug in my generation script, fixed in http://commondatastorage.googleapis.com/ossf-criticality-score/python_top_200.csv

**Comment by Nklya** [comment]
Great, thank you
