### ISSUE TITLE
Can only install the standalone CLI from @main

### ISSUE THREAD

**Issue by pnacht** [ossf/criticality_score#288]
The README suggests installing the CLI with

```shell
go install github.com/ossf/criticality_score/cmd/criticality_score
```

However, I get an error:

```shell
go: 'go install' requires a version when current directory is not in a module
Try 'go install github.com/ossf/criticality_score/cmd/criticality_score@latest' to install the latest version
```

However, when I then try `@latest` (and `@v1.0.7`, the latest release tag), I get another error:

```shell
go: github.com/ossf/criticality_score/cmd/criticality_score@latest: module github.com/ossf/criticality_score@latest found (v1.0.7), but does not contain package github.com/ossf/criticality_score/cmd/criticality_score
```

The only method I've found that works is using `@main`, but that's not an optimal solution since it requires that the main branch be in a usable state.

**Comment by calebbrown** [comment]
Thanks for the feedback @pnacht - I am hoping to set up a binary release process in the not-to-distant future which should make this problem go away.

The "1.0.7" version is a legacy reference to the old Python code and needs to go away.

**Comment by noah-de** [comment]
Is there any way that I could contribute to this effort?

**Comment by gabibguti** [comment]
I believe we can close this issue for now.

**Comment by calebbrown** [comment]
Done, thanks!
