### ISSUE TITLE
criticality_score command line doesn't work

### ISSUE THREAD

**Issue by fredgan** [ossf/criticality_score#328]
Hi, I build the `criticality_score` command and run the command line as below:
```sh
./criticality_score --depsdev-disable=true github.com/ossf/criticality_score
```
But, an error occured.

```
 WARN    Repo cannot be collected        {"worker": 0, "url": "github.com/ossf/criticality_score", "error": "repo failed: unsupported url: github.com/ossf/criticality_score"}
main.main.func1
        D:/Project/third-party/criticality_score/cmd/criticality_score/main.go:202
```

So I go to read and debug the code. I find that `internal/collector/github/factory.go` line57 function
```
func (f *factory) Match(u *url.URL) bool {
	return u.Hostname() == "github.com"
}
```
`u.Hostname()` would be empty string `""`. The reason is that `url.Parse( "github.com/ossf/criticality_score")` won't work but  `url.Parse( "https://github.com/ossf/criticality_score")`  will work.

However, if I try command line `./criticality_score --depsdev-disable=true https://github.com/ossf/criticality_score`，another error occured.
```
ERROR   Failed to prepare input {"error": "open https://github.com/ossf/criticality_score: The filename, directory name, or volume label syntax is incorrect."}
```
So, There should be some error in the logic.

**Comment by calebbrown** [comment]
I was unable to reproduce this, and it looks like we are not handling the errors correctly on Windows.

**Comment by calebbrown** [comment]
Hi, this error should now be fixed.

I've added some unit-tests and now run them on Windows as well to help ensure these problems are caught earlier.

**Comment by JarLob** [comment]
I still can reproduce it, but it can be because the `latest` is still `v1.0.8`:
```
>go install github.com/ossf/criticality_score/cmd/criticality_score@latest
go: downloading github.com/ossf/criticality_score v1.0.8
...
```

Also please release `v2.0.3` of the tool, because https://github.com/ossf/criticality_score/pull/383 didn't make it into `v2.0.2` and it is hard to understand version of the tool is running.
