### ISSUE TITLE
Non-python projects in Python list

### ISSUE THREAD

**Issue by orsinium** [ossf/criticality_score#34]
There are some non-code projects that are considered as Python projects because the only code they have is a few Python scripts:

+ 143: [raspberry pi documentation](https://github.com/raspberrypi/documentation)
+ 171: [toml](https://github.com/toml-lang/toml)

Maybe, more

Possible solutions:

+ Manual sanitization.
+ Threshold of the Python code amount to be considered as Python project

**Comment by inferno-chromium** [comment]
We look at github's language field

https://github.com/raspberrypi/documentation has 72% python code (>27% shell)
https://github.com/toml-lang/toml has 100% python code

**Comment by orsinium** [comment]
Yes, I understand why the issue appears. However, it's still an issue. 

1. Why the RPI docs are included in the list as Python critical project? None of the Python ecosystem projects depends on it.
1. If the scripts are removed from RPI docs or rewritten to Clojure will the project become not critical?
1. Why [toml](https://github.com/toml-lang/toml) is considered as critical but [gitignore](https://github.com/github/gitignore) isn't? It doesn't have a language detected but it is still important. Must a project include a Python script to be considered critical?
1. What if one provides a Python library that has mostly C++ code and quite a thin interface? Why won't be considered as a Python library? Why [tensorflow](https://github.com/tensorflow/tensorflow) is not included but [scikit-learn](https://github.com/scikit-learn/scikit-learn) is?

**Comment by orsinium** [comment]
Another important case: projects with multiple libraries for different languages in one repository. For example, [hypothesis](https://github.com/HypothesisWorks/hypothesis) is included in the list but [z3](https://github.com/Z3Prover/z3) isn't.
