### ISSUE TITLE
need help!!!

### ISSUE THREAD

**Issue by LikeFirstMeet** [ossf/criticality_score#342]
I want to run this project, i have meet a problem,which is "bash criticality_score:commond not found" after i excute "criticality_score github.com/kubernetes/kubernetes",what should i do to run it?

**Comment by fredgan** [comment]
Maybe you can describe this probem more clearly.

From the current description, it seems that you didn't install the file `criticality_score `, so you need to specify the command path, like `./criticality_score github.com/kubernetes/kubernetes`

**Comment by LikeFirstMeet** [comment]
> Maybe you can describe this probem more clearly.
> 
> From the current description, it seems that you didn't install the file `criticality_score `, so you need to specify the command path, like `./criticality_score github.com/kubernetes/kubernetes`

Thank you for your advice.I have solved this problem.I have run it ,but new problem arises ,i need a google default credential.Can i bypass the google default to use this tool?

**Comment by fredgan** [comment]
I think so, you can add an option `--depsdev-disable true` to skip google credential.

**Comment by LikeFirstMeet** [comment]
> I think so, you can add an option `--depsdev-disable true` to skip google credential.

Hello,I excute the command which is "./criticality_score --depsdev-disable true github.com/tensorflow/tensorflow",then it give me some messages,
like "2023-03-27 23:43:09.706	INFO	Preparing default scorer
2023-03-27 23:43:09.706	WARN	deps.dev signal source is disabled.
github.com/ossf/criticality_score/internal/collector.New
	/root/go/src/github.com/criticality_score/criticality_score/internal/collector/collector.go:82
main.main
	/root/go/src/github.com/criticality_score/criticality_score/cmd/criticality_score/main.go:157
runtime.main
	/usr/lib/golang/src/runtime/proc.go:250
2023-03-27 23:43:09.706	WARN	Repo cannot be collected	{"worker": 0, "url": "true", "error": "repo failed: unsupported url: true"}
main.main.func1
	/root/go/src/github.com/criticality_score/criticality_score/cmd/criticality_score/main.go:203
github.com/ossf/criticality_score/internal/workerpool.WorkerPool.func1
	/root/go/src/github.com/criticality_score/criticality_score/internal/workerpool/workerpool.go:36".
It seems work,but it can't collect specific reposity data.How can i do to solve it?If not,does this tool import text file and run to get a criticality score?Very thank you!

**Comment by calebbrown** [comment]
You don't need the `true` in your command:

Try:
```
./criticality_score --depsdev-disable github.com/tensorflow/tensorflow
```

**Comment by LikeFirstMeet** [comment]
> You don't need the `true` in your command:
> 
> Try:
> 
> ```
> ./criticality_score --depsdev-disable github.com/tensorflow/tensorflow
> ```

I have tried the commond,and it give me the same mistake.Can you run this command without error!If yes,i thank my network environment can't access the specific remote repository.

**Comment by LikeFirstMeet** [comment]
> You don't need the `true` in your command:
> 
> Try:
> 
> ```
> ./criticality_score --depsdev-disable github.com/tensorflow/tensorflow
> ```

Hello,I git rid of the error by excuting "./criticality_score --depsdev-disable https://github.com/tensorflow/tensorflow".
And now,i want to know the differences between using gcp accout or using --depsdev-disable ,when i run this project!!!

**Comment by LikeFirstMeet** [comment]
> Maybe you can describe this probem more clearly.
> 
> From the current description, it seems that you didn't install the file `criticality_score `, so you need to specify the command path, like `./criticality_score github.com/kubernetes/kubernetes`

Hi,brother!Do you know the differences between using gcp account or using '--devpsdev-disable' while runing this project?

**Comment by fredgan** [comment]
> > Maybe you can describe this probem more clearly.
> > From the current description, it seems that you didn't install the file `criticality_score `, so you need to specify the command path, like `./criticality_score github.com/kubernetes/kubernetes`
> 
> Hi,brother!Do you know the differences between using gcp account and using '--devpsdev-disable' while runing this project?

Sorry, I don't have GCP account either.
