### ISSUE TITLE
Critical dependant

### ISSUE THREAD

**Issue by kof** [ossf/criticality_score#35]
If a package Y depends on package X. Y has score 1, X has score 0.5. Shouldn't the score X reflect the score Y to a certain degree?

As an example - a very popular package heavily relies on some other package, which is less known, has lower score on all data points, but actually is super critical to all users of the popular package.

**Comment by inferno-chromium** [comment]
Yes, do agree, but need more ideas to process this, there is some discussion in https://github.com/ossf/criticality_score/issues/8, so lets continue it there.
