### ISSUE TITLE
What is dependents_count parameter, looks suspect ?

### ISSUE THREAD

**Issue by lgritz** [ossf/criticality_score#39]
I asked for the criticality info on several projects in my industry's ecosystem, and the dependents_count really confuses me and makes me suspicious about how it's computed. Some of the projects I checked are hard dependencies of others, so if transitive dependencies are being properly tracked, the former should always have higher dependents_count than the latter, no? But this is not the case.

One project that I run is very specialized and is of no use to casual small projects, only making sense as an embedded component of a large open source or commercial app. So while certainly very important in my industry and having a large number of end users touch those things in which it is embedded, I expect it to have a tiny number of directly downstream projects.  Yet it has an absurdly, implausibly high dependents_count. Other projects I checked on that I know are directly used by orders of magnitude more projects, have implausibly low dependents_count.

Is there some kind of verbose mode that prints details that would give us more information about how these scores are computed? Like, more insight into why it thinks a project has few or many dependent projects?

I should mention that these are C++ projects, so perhaps the means by which dependencies are tracked is very flawed compared to a python (say) which may have a requirements.txt. How is it computed for C++? Has anybody considered promoting a GitHub convention of having a particularly named file serve as a manifest for what other projects a code base is dependent on? (Informationally only, since no C++ build system cares about such things.)

**Comment by inferno-chromium** [comment]
I don't think it is possible for C/C++ projects, this is why we came up with a generic dependent_counts using commit mentions [it just means we want to see how many other oss repo roll this project in a commit]. We want to expand this to use dependency graph where is available [e.g. #31], but that still does not give any info on how it is used. 
Inside google, we used the additional --params field to add package usage in criticality score algo (like weight=10 or 50%, and rest of criticality factors].

**Comment by inferno-chromium** [comment]
Here is the code:
https://github.com/ossf/criticality_score/blob/main/criticality_score/run.py#L142

Also, adding file is a manual process, it does not scale well, need to think of something that is automatable. Of course, this is still good to pursue longer term with underlying build tools like ninja, bazel, etc.

**Comment by lgritz** [comment]
What do you mean by "roll this project in a commit"? You mean have it as a git submodule? Or do you mean that the name of the project shows up anywhere in the other project's commit messages? And if the latter, is it looking for the repo name? That may or may not match the name people use to colloquially refer to the project.

Is there anything that maintainers of a mostly C++ project can do to make it easier for the system to correctly track its dependencies and downstream projects?

**Comment by lgritz** [comment]
Semi-related: I'm also seeing the criticality score's reporting of number of contributors not matching what GitHub says are the number of committers.

**Comment by inferno-chromium** [comment]
> Semi-related: I'm also seeing the criticality score's reporting of number of contributors not matching what GitHub says are the number of committers.

File a bug with an example but first check it with number of contributors given on the bottom right of a github page for that project.

**Comment by inferno-chromium** [comment]
> What do you mean by "roll this project in a commit"? You mean have it as a git submodule? Or do you mean that the name of the project shows up anywhere in the other project's commit messages? And if the latter, is it looking for the repo name? That may or may not match the name people use to colloquially refer to the project.

In commit message, people usually mention the repo name if they are rolling forward an update for that library or first use.

> 
> Is there anything that maintainers of a mostly C++ project can do to make it easier for the system to correctly track its dependencies and downstream projects?

We can come up with standard, but it only matters if lets say most projects like 70-80% use it. That is why getting into build tools is much better. for other languages, it is in package managers.
