### ISSUE TITLE
How are the top 200 lists computed?

### ISSUE THREAD

**Issue by lgritz** [ossf/criticality_score#40]
I am directly responsible for two open source projects. I was shocked to see that one is on your "top 200" list of C++ projects. The other project has been around longer, has more contributors, more PRs, surely has an order of magnitude more downstream users, and in fact has a much higher criticality score. But it's not on the list. I can't quite figure out what the top 200 would be measuring (I would think the 200 projects with the very highest criticality score itself? But apparently not?) for the first project to show up on the list but not the other.

Can you give any insight about WHAT is being ranked in your "top" lists?

**Comment by inferno-chromium** [comment]
See https://github.com/ossf/criticality_score/blob/main/criticality_score/run.py
Basically there is a github search api bug we are trying to workaround [github search only gives top 1000 results]. We get the top 1000 repos by stars for a language and then sort them by criticality score. This is not great, we want to run this over a much bigger sample set, atleast >10K. We have a fix now at https://github.com/ossf/criticality_score/pull/38

Can you give the two repos links ? I am pretty sure it is the stars issue if criticality issue for other is higher.

**Comment by lgritz** [comment]
Oh, so you're saying that it was the top 200 *out of an arbitrary group of 1000 projects*, so maybe one project by chance was in that initial 1000 returned by the query but the other was not?

If I understand it, that would explain things. But if you are curious, here are the two projects I'm referring to:

On 200 list, lower criticality score: https://github.com/imageworks/OpenShadingLanguage/
Not on list, higher criticality score: https://github.com/OpenImageIO/oiio

**Comment by inferno-chromium** [comment]
> Oh, so you're saying that it was the top 200 _out of an arbitrary group of 1000 projects_, so maybe one project by chance was in that initial 1000 returned by the query but the other was not?

Not random Sir :) it returns the top 1000 projects sorted in descending order by stars [and github api does not go beyond 1000, we now found a workaround and also github per project processing is super slow, so will start with 5000 and increase later, 5000 should bring most]. 

> 
> If I understand it, that would explain things. But if you are curious, here are the two projects I'm referring to:
> 
> On 200 list, lower criticality score: https://github.com/imageworks/OpenShadingLanguage/
> Not on list, higher criticality score: https://github.com/OpenImageIO/oiio

Yes same issue as https://github.com/ossf/criticality_score/issues/33, closing it here.

**Comment by lgritz** [comment]
I see, thanks for the clarification.
