### ISSUE TITLE
Criticality score usage failed

### ISSUE THREAD

**Issue by hogo6002** [ossf/criticality_score#405]
The [usage](https://github.com/ossf/criticality_score#usage) page shows an example with the URL github.com/kubernetes/kubernetes. However, it failed with this URL. The criticality_score tool can only run URLs with an https prefix. For example, https://github.com/kubernetes/kubernetes.

>~/go/bin$ ./criticality_score -gcp-project-id=clusterfuzz-external github.com/kubernetes/kubernetes
2023-06-02 11:13:49.777	INFO	Preparing default scorer
2023-06-02 11:13:50.901	INFO	deps.dev signal source enabled
**2023-06-02 11:13:50.902	WARN	Repo cannot be collected	{"worker": 0, "url": "github.com/kubernetes/kubernetes", "error": "repo failed: unsupported url: github.com/kubernetes/kubernetes"}**
main.main.func1
	/usr/local/google/home/gongh/go/pkg/mod/github.com/ossf/criticality_score@v1.0.8/cmd/criticality_score/main.go:202
github.com/ossf/criticality_score/internal/workerpool.WorkerPool.func1
	/usr/local/google/home/gongh/go/pkg/mod/github.com/ossf/criticality_score@v1.0.8/internal/workerpool/workerpool.go:36

**Comment by coni2k** [comment]
@hogo6002 Could you try it by adding "https://" in front of the repo?

```
~/go/bin$ ./criticality_score -gcp-project-id=clusterfuzz-external https://github.com/kubernetes/kubernetes
```
