### ISSUE TITLE
Generate a list for PHP projects

### ISSUE THREAD

**Issue by kick-the-bucket** [ossf/criticality_score#41]

**Comment by inferno-chromium** [comment]
Sure, will do, right now fixing some bugs with generation script, but will be able to do this sometime this week.

**Comment by kick-the-bucket** [comment]
Thanks ;)

**Comment by inferno-chromium** [comment]
http://commondatastorage.googleapis.com/ossf-criticality-score/php_top_200.csv with default generate script params [sample-size=top 5000 by star desc, then sort by criticality score, pick top 200]
