### ISSUE TITLE
`go install latest` pulls v1.0.8

### ISSUE THREAD

**Issue by JarLob** [ossf/criticality_score#412]
```
>go install github.com/ossf/criticality_score/cmd/criticality_score@latest
go: downloading github.com/ossf/criticality_score v1.0.8
...
```

Also please release `v2.0.3` of the tool, because https://github.com/ossf/criticality_score/pull/383 didn't make it into `v2.0.2` and it is hard to understand what version of the tool is running.

**Comment by JarLob** [comment]
This [thread](https://stackoverflow.com/questions/75534660/how-to-deal-with-go-vanity-urls-and-major-version-sub-packages) can be useful for fixing the issue.

**Comment by calebbrown** [comment]
v2.0.3 has no been released and the docs for these commands have been updated.

Please try `go install github.com/ossf/criticality_score/v2/cmd/criticality_score@latest`
