### ISSUE TITLE
Short interview?

### ISSUE THREAD

**Issue by LawrenceHecht** [ossf/criticality_score#46]
Can I briefly talk to someone about how 1) the wish list of criteria that wasn't included in the algorithm and 2) the nuances of how the data is being used to pick candidates for security audits?  This could inform an article I will write, but I can also use the information to help coordinate your activities with some other projects I am in communication with.

**Comment by inferno-chromium** [comment]
Sure, can drop an email at inferno dot chromium dot org
reasoning column has been updated in docs - https://github.com/ossf/criticality_score#criticality-score
