### ISSUE TITLE
Provide reasoning for current parameter selection

### ISSUE THREAD

**Issue by kiview** [ossf/criticality_score#48]
The current implementation takes the following parameters (with specific weights and threshold) into account:

- created_since
- updated_since
- contributor_count
- org_count
- commit_frequency
- recent_releases_count
- closed_issues_count
- updated_issues_count
- comment_frequency
- dependents_count

While I assume there is some clear motivation for the current selection, there seems to be no publicly available reasoning giving indications why exactly this set of parameters was chosen (although it might exist somewhere or might have emerged from working group discussion and other empirical analyses).

Adding such reasoning would greatly improve the transparency of the formula and foster more debate about potentially tuning it or decreasing encoded bias.

**Comment by inferno-chromium** [comment]
Good point, let me add to README.md, this was discussed in a google doc.

**Comment by aalmiray** [comment]
How does the formula take into consideration:

- projects that do not use Github issues?
- projects that require more than one repository?
- projects where there's more interaction in external forums (mailing lists for example) which may result in fewer commits?
- projects hosted at locations other than Github? (Gitlab, Surceforge, ...)
- how do merge commit, squashed commits affect the results?

**Comment by inferno-chromium** [comment]
We have not solved these, ideas/PR welcome.

> How does the formula take into consideration:
> 
> * projects that do not use Github issues?

https://github.com/ossf/criticality_score/issues/21

> * projects that require more than one repository?

https://github.com/ossf/criticality_score/issues/21

> * projects where there's more interaction in external forums (mailing lists for example) which may result in fewer commits?

kind of https://github.com/ossf/criticality_score/issues/21

> * projects hosted at locations other than Github? (Gitlab, Surceforge, ...)

https://github.com/ossf/criticality_score/issues/29 [atleast gitlab can come since there is a python lib]

> * how do merge commit, squashed commits affect the results?

that is not accounted, but that shouldnt be frequent. thoughts ?
