### ISSUE TITLE
Kotlin as Java language

### ISSUE THREAD

**Issue by yschimke** [ossf/criticality_score#50]
Is it fair to add Kotlin into the java language map here?  What about Scala as well.  Every Java or Scala project will include large swatches of the Java ecosystem, and Kotlin has large developer mindshare on Android and increasingly in server space with Ktor etc.

```
    'java': ['Java', 'Groovy'],
```

**Comment by inferno-chromium** [comment]
Thanks, add Kotlin and Scala to this list.

Java list will be regenerated in the next few days, everything will be regenerated due to this project age fix.
