### ISSUE TITLE
why apache/spark isn't in Java top 200 public data?

### ISSUE THREAD

**Issue by Dieken** [ossf/criticality_score#54]
Spark has much higher score than ElasticSearch and Beam, Spark is missing but ElasticSearch and Beam are there, why?

apache/spark:
```
$ criticality_score --repo github.com/apache/spark
name: spark
url: https://github.com/apache/spark
language: Scala
created_since: 83
updated_since: 0
contributor_count: 2374
org_count: 4
commit_frequency: 53.8
recent_releases_count: 20
closed_issues_count: 1252
updated_issues_count: 1456
comment_frequency: 12.1
dependents_count: 396346
criticality_score: 0.96476
```

elastic/elasticsearch:
```
$ criticality_score --repo github.com/elastic/elasticsearch
name: elasticsearch
url: https://github.com/elastic/elasticsearch
language: Java
created_since: 132
updated_since: 0
contributor_count: 1709
org_count: 3
commit_frequency: 127.1
recent_releases_count: 21
closed_issues_count: 7966
updated_issues_count: 9234
comment_frequency: 1.0
dependents_count: 95320
criticality_score: 0.88175
```

apache/beam:
```
$ criticality_score --repo github.com/apache/beam
name: beam
url: https://github.com/apache/beam
language: Java
created_since: 59
updated_since: 0
contributor_count: 980
org_count: 7
commit_frequency: 67.1
recent_releases_count: 7
closed_issues_count: 725
updated_issues_count: 826
comment_frequency: 4.3
dependents_count: 11397
criticality_score: 0.8319
```

**Comment by inferno-chromium** [comment]
The generation script is updated, but it is in process of being generated. I am regenerating all languages due to https://github.com/ossf/criticality_score/commit/8c88dbaa3ffb62e7b423641d3e34219db33fa123, so it will take like a week. hopefully java should be done soonish, but cant guarantee. I just wish github api could be faster, and right now, the process is not scaled across nodes (limited api accounts).

**Comment by Dieken** [comment]
Got it, the old script didn't count Kotlin and Scala 😄️

Shall we include Clojure in Java too?

**Comment by inferno-chromium** [comment]
> Got it, the old script didn't count Kotlin and Scala 😄️
> 
> Shall we include Clojure in Java too?

can upload a PR to add it, but that one wont make it in this run, will get in next run probably in next two weeks or so.

**Comment by inferno-chromium** [comment]
data regenerated.
