### ISSUE TITLE
Update Readme to include Gitlab dependency?

### ISSUE THREAD

**Issue by coni2k** [ossf/criticality_score#59]
I just retrieved the latest version:
https://github.com/ossf/criticality_score/commit/82b1237223f3954be008cc794b8c1753eb7c963e

When I run the script to generate the list, I was receiving `No module named 'gitlab` error message:

```
> python -u -m criticality_score.generate --language c --count 1 --sample-size 1

Traceback (most recent call last):
  File "...\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "...\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\criticality_score\generate.py", line 22, in <module>
    from . import run
  File "...\criticality_score\run.py", line 28, in <module>
    import gitlab
ModuleNotFoundError: No module named 'gitlab'
```

The problem is solved when I installed python-gitlab module:
pip install python-gitlab

My knowledge about Python is very limited but should we mention this dependency in Readme file?

**Comment by inferno-chromium** [comment]
Thanks, fixed docs.

Just fyi, language lists are generated and available to see at https://ossf-criticality-score.storage.googleapis.com/index.html
