### ISSUE TITLE
How can I quickly get scores for a list of repos?

### ISSUE THREAD

**Issue by ljharb** [ossf/criticality_score#97]
I have 300+ repos, across 6+ github orgs. How can I quickly determine where there's room for improvement? Setting up a github action on every repo would be quite onerous, and it'd be easy to miss one.

fwiw, I already have a script that can get me a list of all the repos I care about from Github's API; what should be my next step?

**Comment by lehors** [comment]
Hi, I just posted a PR to allow giving criticality_score a list of projects to score. I'd be interested to know whether this helps with your problem.
Thanks.

**Comment by calebbrown** [comment]
The new `./cmd/criticality_score` binary supports a file containing a list of repos, one per each line.

Format can be changed using `-format={text,csv,json}` as well.

**Comment by ljharb** [comment]
Thanks!
